### ISSUE TITLE
Not working on private repos

### ISSUE THREAD

**Issue by mkny** [divykj/wakatime-charts#4]
I'm probably missing something out, but for my project, it keeps getting me the error:

`fatal: could not read Username for 'https://github.com': No such device or address`

Here is my yaml config:

```yaml
name: Wakatime Charts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

jobs:
  update-charts:
    name: Update wakatime stats charts
    runs-on: ubuntu-latest
    steps:
      - uses: divykj/wakatime-charts@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
```
